---
- hosts: all
  become: no
  tasks:
  - name: Get current time
    ansible.builtin.command: date +"%Y-%m-%d %H:%M:%S"
    register: current_time
    changed_when: false
    
  - name: Write current time
    ansible.builtin.copy:
      content: "{{ current_time.stdout }}\n"
      dest: "~/time"
      mode: '0644'
      
  - name: Write username
    ansible.builtin.copy:
      content: "{{ ansible_user_id }}\n"
      dest: "~/username"
      mode: '0644'